services:
  database:
    image: mysql:8.0
    container_name: cnps_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cnps_recommandations
      MYSQL_USER: cnps_user
      MYSQL_PASSWORD: cnps_pass
    ports:
      - "3307:3306"
    volumes:
      - cnps_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cnps_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    depends_on:
      database:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    container_name: cnps_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  cnps_mysql_data: